# Promise then callbacks II

```js
Promise.resolve(1)
  .then((val) => {
    console.log(val);
    return val + 1;
  })
  .then((val) => {
    console.log(val);
  })
  .then((val) => {
    console.log(val);
    return Promise.resolve(3).then((val) => {
      console.log(val);
    });
  })
  .then((val) => {
    console.log(val);
    return Promise.reject(4);
  })
  .catch((val) => {
    console.log(val);
  })
  .finally((val) => {
    console.log(val);
    return 10;
  })
  .then((val) => {
    console.log(val);
  });
```

[Problem Link](https://bigfrontend.dev/quiz/4-Promise-then-callbacks-II)

## Solution

```
1
2
undefined
3
undefined
4
undefined
undefined
```

## Explanation

When we handle a settled promise using `then` it expects two optional callbacks viz. resolved and rejected handlers. If nothing is returned from handler functions, it implicitly returns `undefined` that is passed onto the further chain

> A finally callback will not receive any argument, since there's no reliable means of determining if the promise was fulfilled or rejected.

This is why, here the `val` passed to `finally` block is `undefined`.

Also, `finally` will not pass in values further in the chain even if we return some value explictily.

```js
Promise.resolve(1)
  .then((val) => {
    console.log(val); // 1
    return val + 1; // chains 2
  })
  .then((val) => {
    console.log(val); // 2
    // chains undefined implicitly
  })
  .then((val) => {
    console.log(val); // undefined
    return Promise.resolve(3).then((val) => {
      console.log(val); // 3
    }); // value undefined is return
  })
  .then((val) => {
    console.log(val); // undefined
    return Promise.reject(4); // 4 is returned
  })
  .catch((val) => {
    console.log(val); // 4
  })
  .finally((val) => {
    // finally callback doesn't receive any argument, val will always be undefined
    console.log(val); // undefined
    return 10; // since finally is already called, passing 10 makes no difference
  })
  .then((val) => {
    console.log(val); // undefined as finally has already been called
  });
```
