# Promise executor IV

```js
const promise = new Promise((resolve, reject) => {
  const promise2 = Promise.reject("error").then(
    () => {
      console.log(1);
    },
    () => {
      console.log(2);
    }
  );
  resolve(promise2);
});
promise.then(console.log);
```

[Problem Link](https://bigfrontend.dev/quiz/Promise-executor-IV)

## Solution

```
2
undefined
```

## Explanation

Here, for `promise` the executor function is executed immediately by the Promise implementation. Since `promise2` is a rejected promise, the 2nd callback to `then` gets executed and `2` is logged to the console. However, since no value is returned explicitly, the fulfilled value for `promise2` remains `undefined`

`promise` then ultimately resolves with the value returned from `promise2` i.e. `undefined` which gets logged to the console when `promise.then` gets invoked

```js
const promise = new Promise((resolve, reject) => {
  const promise2 = Promise.reject("error").then(
    () => {
      console.log(1);
    },
    () => {
      console.log(2);
    }
  );
  resolve(promise2);
});
promise.then(console.log);

// 2
// undefined
```
