# Generator return()

```js
function* gen() {
  yield 1;
  try {
    yield 2;
    yield 3;
  } finally {
    yield 4;
  }
  yield 5;
}

const g = gen();
console.log(g.next().value);
console.log(g.next().value);
console.log(g.return(6).value);
console.log(g.next().value);
console.log(g.next().value);
```

[Problem Link](https://bigfrontend.dev/quiz/generator-return)

## Solution

```
1
2
4
6
undefined
```

## Explanation

> The [return()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return) method of Generator instances acts as if a return statement is inserted in the generator's body at the current suspended position.

However, if the yield expression is wrapped in a try...finally block, the control flow doesn't exit the function body, but proceeds to the finally block instead. Also, If an argument is provided to return(), it becomes the value property of the returned object.

In this example, we invoke the `gen()` generator which doesn't execute it immediately but rather suspends it. Using `g.next()` resumes it and returns the yielded value. Thus, we see 1 and 2 logged sequentially.

When we do `g.return(6).value`, execution in the generator proceeds to the finally block and 4 is yielded and logged. The returned value 6 is then logged by the next `g.next().value` and at that time the generator finally is completed. Hence, calling [next()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/next) again simply returns `undefined`.

```
function* gen() {
  yield 1
  try {
    yield 2
    yield 3
  } finally {
    yield 4
  }
  yield 5
}

const g = gen()
console.log(g.next().value) // 1
console.log(g.next().value) // 2
console.log(g.return(6).value) // 4
console.log(g.next().value) // 6
console.log(g.next().value) // undefined
```
