# return in Generator 2

```js
function* g() {
  console.log(1);
  try {
    console.log(2);
    yield 2;
    console.log(3);
    throw new Error("error");
  } finally {
    console.log(4);
  }
}

const obj = g();
obj.next();
obj.return();
```

[Problem Link](https://bigfrontend.dev/quiz/return-gen)

## Solution

```
1
2
4
```

## Explanation

In this example, we have a [generator function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return) `g` which is invoked when we run `g()`. However, this does not immediately start the execution but rather pauses it.

`obj.next()` will resume the generator and we see 1 logged to console. Next up, we see 2 logged as the `try` block gets executed. The [yield](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield) keyword will yield the value 2 and generator is paused again.

`obj.return` i.e. [Generator.return()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator/return) method acts as if a `return` statement is inserted in the generator's body at the current suspended position. This finishes the generator and allows the generator to move on to the `finally` block. Hence, 4 gets logged.

```
function* g() {
  console.log(1);
  try {
    console.log(2)
    yield 2
    console.log(3)
    throw new Error('error')
  } finally {
    console.log(4)
  }
}

const obj = g()
obj.next()
obj.return()

// 1
// 2
// 4
```
